# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 739)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/dx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(14.0)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_1 = QtWidgets.QLabel(self.centralwidget)
        self.Image_1.setGeometry(QtCore.QRect(10, 40, 261, 271))
        self.Image_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Image_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image_1.setText("")
        self.Image_1.setObjectName("Image_1")
        self.Image_2 = QtWidgets.QLabel(self.centralwidget)
        self.Image_2.setGeometry(QtCore.QRect(10, 360, 261, 271))
        self.Image_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Image_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image_2.setText("")
        self.Image_2.setObjectName("Image_2")
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setGeometry(QtCore.QRect(290, 10, 241, 22))
        self.comboBox_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 0, 0);\n"
"")
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.DisplayIm_1 = QtWidgets.QPushButton(self.centralwidget)
        self.DisplayIm_1.setGeometry(QtCore.QRect(60, 10, 93, 28))
        self.DisplayIm_1.setAutoFillBackground(False)
        self.DisplayIm_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(170, 0, 0);")
        self.DisplayIm_1.setIconSize(QtCore.QSize(40, 40))
        self.DisplayIm_1.setCheckable(False)
        self.DisplayIm_1.setAutoRepeat(False)
        self.DisplayIm_1.setAutoExclusive(False)
        self.DisplayIm_1.setAutoDefault(False)
        self.DisplayIm_1.setDefault(False)
        self.DisplayIm_1.setFlat(False)
        self.DisplayIm_1.setObjectName("DisplayIm_1")
        self.DisplayIm_2 = QtWidgets.QPushButton(self.centralwidget)
        self.DisplayIm_2.setGeometry(QtCore.QRect(70, 320, 93, 28))
        self.DisplayIm_2.setAutoFillBackground(False)
        self.DisplayIm_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(170, 0, 0);")
        self.DisplayIm_2.setIconSize(QtCore.QSize(40, 40))
        self.DisplayIm_2.setCheckable(False)
        self.DisplayIm_2.setAutoRepeat(False)
        self.DisplayIm_2.setAutoExclusive(False)
        self.DisplayIm_2.setAutoDefault(False)
        self.DisplayIm_2.setDefault(False)
        self.DisplayIm_2.setFlat(False)
        self.DisplayIm_2.setObjectName("DisplayIm_2")
        self.output_1 = QtWidgets.QLabel(self.centralwidget)
        self.output_1.setGeometry(QtCore.QRect(560, 360, 251, 271))
        self.output_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.output_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.output_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_1.setText("")
        self.output_1.setObjectName("output_1")
        self.output_2 = QtWidgets.QLabel(self.centralwidget)
        self.output_2.setGeometry(QtCore.QRect(810, 360, 251, 271))
        self.output_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.output_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.output_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_2.setText("")
        self.output_2.setObjectName("output_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(860, 330, 201, 22))
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 0, 0);\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 330, 241, 22))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 0, 0);\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.Image_3 = QtWidgets.QLabel(self.centralwidget)
        self.Image_3.setGeometry(QtCore.QRect(290, 40, 261, 271))
        self.Image_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Image_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image_3.setText("")
        self.Image_3.setObjectName("Image_3")
        self.Image_4 = QtWidgets.QLabel(self.centralwidget)
        self.Image_4.setGeometry(QtCore.QRect(280, 360, 261, 271))
        self.Image_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Image_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image_4.setText("")
        self.Image_4.setObjectName("Image_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(610, 0, 441, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout.addWidget(self.horizontalSlider_2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(170, 0, 0);\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "Choose"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "FT Magnitude"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "Inverse FT Magnitude"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "FT Phase"))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "Inverse FT Phase"))
        self.comboBox_1.setItemText(5, _translate("MainWindow", "FT Real "))
        self.comboBox_1.setItemText(6, _translate("MainWindow", "FT Imaginary "))
        self.comboBox_1.setItemText(7, _translate("MainWindow", "UniForm Phase"))
        self.comboBox_1.setItemText(8, _translate("MainWindow", "UniForm Magnitude"))
        self.DisplayIm_1.setAccessibleName(_translate("MainWindow", "<html><head/><body><p>m,mm,</p></body></html>"))
        self.DisplayIm_1.setText(_translate("MainWindow", "DisplayIm_1"))
        self.DisplayIm_2.setAccessibleName(_translate("MainWindow", "<html><head/><body><p>m,mm,</p></body></html>"))
        self.DisplayIm_2.setText(_translate("MainWindow", "DisplayIm_2"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Choose"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "OutPut_1"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "OutPut_2"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Choose"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "FT Magnitude"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Inverse FT Magnitude"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "FT Phase"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Inverse FT Phase"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "FT Real "))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "FT Imaginary "))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "UniForm Phase"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "UniForm Magnitude"))
        self.label.setText(_translate("MainWindow", " magnitudeOrRealRatio"))
        self.label_2.setText(_translate("MainWindow", "phaesOrImaginaryRatio"))
        self.radioButton.setText(_translate("MainWindow", "Image_1"))
        self.radioButton_2.setText(_translate("MainWindow", "image_2"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Choose"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Phase and Magnitude Mode"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Real and Imaginary Mode"))
